name: CI Maven Project

on:
  workflow_dispatch:
    inputs:
      TARGE_ENVIRONMENT:
        type: environment
        default: dev

jobs:
  
  call-reusable:
    name: Call Reusable Workflow
    uses: ./.github/workflows/reused.yml
    with:
     environment: ${{ inputs.TARGE_ENVIRONMENT }}


  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.TARGE_ENVIRONMENT }}
    needs: call-reusable

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Build with Maven
        run: mvn clean install

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: java-build
          path: target/*.jar

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Run Maven Tests
        run: mvn test

  package:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v5.0.0
        with:
          name: java-build
          path: staging

      - name: List downloaded files
        run: ls staging

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: package

    steps:
      - name: Deployment Step
        run: |
          echo "Deploying application..."
          echo "Environment: ${{ inputs.TARGE_ENVIRONMENT }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"
          echo "Commit: ${{ github.sha }}"
